In [16]:
# Import pandas
import pandas as pd
# reading csv file
data=pd.read_csv("data.csv")
#
print("\n Whole DataSet")
print(data)
#

# print(data.head(2))
# # #
# print(data.tail(2))
# # #
# print(data.describe())
# # #
desc = data["area"].describe()


print(desc)
#
print("Sum",data["area"].sum())
# #
print("Max",data["area"].max())
print("Min",data["area"].min())
print("Average",data["area"].mean())
print("Count",data["area"].count())
# # #
print(data["area" ])
# # #
print("\n 0 to 2 Records usiing ILOC")
print(data.iloc[0:2])
print("\n 0 to 2 Records usiing LOC")
print(data.loc[0:2])
print("\n From 2 onwards Records usiing ILOC")
print(data.iloc[2:])
print("\n Till 4 Records usiing ILOC")
print(data.iloc[:4])
# #
# #
print("\n Country India DataSet")
ndata=(data["country" ]=="India")
print(ndata)

print("\n Country India DataSet")

ndata=data[data["country" ]=="India"]
print(ndata)

print("\n Population above <3000 DataSet")

pop=data[data["population"]>3000]
print(pop)

print("\n Population above <3000 and area >8 DataSet")
pop2=data[ (data["population"]>3000) &  (data["area"]>8)]
print(pop2)

# #
# #
print("\n Information DataSet")

print(data.info())
# #
print("\n Size of DataSet")
print(data.shape)
# #
print("\n Check DataSet is NULL")

print(data.isnull())
print(data["area" ].sum())

 Whole DataSet
        country       capital    area  population
0        Brazil    "Brasilia"   8.516       700.0
1        Russia      "Moscow"  17.100      5644.0
2         India   "New Dehli"   3.286      1252.0
3         China     "Beijing"   9.597      1357.0
4  South Africa      Pretoria   1.221      4533.0
5           USA      New York  31.221      1533.0
6            UK        London  13.221       200.0
7         Japan           NaN     NaN         NaN
count     7.000000
mean     12.023143
std      10.057976
min       1.221000
25%       5.901000
50%       9.597000
75%      15.160500
max      31.221000
Name: area, dtype: float64
Sum 84.16199999999999
Max 31.221
Min 1.221
Average 12.023142857142858
Count 7
0     8.516
1    17.100
2     3.286
3     9.597
4     1.221
5    31.221
6    13.221
7       NaN
Name: area, dtype: float64

 0 to 2 Records usiing ILOC
  country      capital    area  population
0  Brazil   "Brasilia"   8.516       700.0
1  Russia     "Moscow"  17.100      5644.0

 0 to 2 Records usiing LOC
  country       capital    area  population
0  Brazil    "Brasilia"   8.516       700.0
1  Russia      "Moscow"  17.100      5644.0
2   India   "New Dehli"   3.286      1252.0

 From 2 onwards Records usiing ILOC
        country       capital    area  population
2         India   "New Dehli"   3.286      1252.0
3         China     "Beijing"   9.597      1357.0
4  South Africa      Pretoria   1.221      4533.0
5           USA      New York  31.221      1533.0
6            UK        London  13.221       200.0
7         Japan           NaN     NaN         NaN

 Till 4 Records usiing ILOC
  country       capital    area  population
0  Brazil    "Brasilia"   8.516       700.0
1  Russia      "Moscow"  17.100      5644.0
2   India   "New Dehli"   3.286      1252.0
3   China     "Beijing"   9.597      1357.0

 Country India DataSet
0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
Name: country, dtype: bool

 Country India DataSet
  country       capital   area  population
2   India   "New Dehli"  3.286      1252.0

 Population above <3000 DataSet
        country    capital    area  population
1        Russia   "Moscow"  17.100      5644.0
4  South Africa   Pretoria   1.221      4533.0

 Population above <3000 and area >8 DataSet
  country    capital  area  population
1  Russia   "Moscow"  17.1      5644.0

 Information DataSet
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     8 non-null      object
 1   capital     7 non-null      object
 2   area        7 non-null      float64
 3   population  7 non-null      float64
dtypes: float64(2), object(2)
memory usage: 384.0+ bytes
None

 Size of DataSet
(8, 4)

 Check DataSet is NULL
   country  capital   area  population
0    False    False  False       False
1    False    False  False       False
2    False    False  False       False
3    False    False  False       False
4    False    False  False       False
5    False    False  False       False
6    False    False  False       False
7    False     True   True        True
84.16199999999999